### ISSUE TITLE
데모에서 Windows 에서는 컬럼 헤더가 잘려서 보이는 현상이 있습니다.

### ISSUE THREAD

**Issue by ysyang1973** [thomasJang/react-frame-datagrid#11]
컬럼 헤더가 잘려서 보이는 현상이 있습니다.

![image](https://user-images.githubusercontent.com/110577569/192302186-b793e1a7-27a1-4ebd-8922-88ccd8d3441d.png)

Windows 11, Chrome 버전 105.0.5195.127(공식 빌드) (64비트) 사용 중

**Comment by thomasJang** [comment]
제 프로젝트에 관심 가져 주셔서 감사합니다.
아이디 컬럼에 sortdisable상태로 예제를 만들어서 오해가 있었던 것 같습니다. 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/5884902/192411839-04514f6e-68ad-4157-97fe-15ded8d4d0b4.png">
그래서 예제를 수정했습니다.
감사합니다.
